// Generated by tools/mktracks.py. Do not edit by hand.
// Circuit dimensions shared by the generator and the game.
#ifndef TRACKS_DIMS_H
#define TRACKS_DIMS_H

#define TRACK_HALF_W      150      // half the road width
#define TRACK_WORLD       16384    // circuits lie inside 0..TRACK_WORLD on x and z
#define TRACK_CELL_SHIFT  7        // nearest-road grid: cells of 1 << shift units,
#define TRACK_GRID        128      // TRACK_GRID across
#define TRACK_PCELL_SHIFT 9        // scenery grid: cells of 1 << shift units,
#define TRACK_PGRID       32       // TRACK_PGRID across

#endif
